apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: api
          # image: registry.digitalocean.com/carbon-server/product:0.1
          image: kandit/product:0.1
          ports:
            - containerPort: 5000
          env:
            - name: PRODUCT_SERVICE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: product-service-secret
                  key: PRODUCT_SERVICE_DATABASE_URL
            - name: CARBON_SERVER_LOG_DB
              valueFrom:
                secretKeyRef:
                  name: product-service-secret
                  key: CARBON_SERVER_LOG_DB
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  ports:
    - port: 80
      name: http
      targetPort: 5000
  selector:
    app: product
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product
  namespace: default
  annotations:
    konghq.com/methods: 'GET,POST'
    konghq.com/plugins: carbon-auth

spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /api/products
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 80
